# Generated by Django 5.0.3 on 2024-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('serial_number', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'ITEMS DATA',
            },
        ),
    ]
